services:
  backend:
    image: e-learning-hub-backend
    restart: always
    env_file: backend/.env.prod
    build: backend
    command: gunicorn --worker-class gevent --workers 2 --bind 0.0.0.0:3000  wsgi:app --log-level debug


  frontend:
    image: e-learning-hub-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile


  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend